#  LLM API 설정
llm:
  provider: "openai"
  model: "gpt-5"
  parameters:
    temperature: 0.3    
    max_tokens: 4096    
    timeout: 120       

#  파일 및 디렉토리 경로 설정
paths:
  benchmarks: "./data/benchmarks/"
  prompts: "./data/prompts/"
  results: "./results/"
  logs: "./results/logs/"

#  MAESTRO 프레임워크 핵심 파라미터
maestro_framework:
  quality_gate:
    success_threshold: 85  
    max_retries: 1         

  # NFR 품질 점수 계산을 위한 상세 기준 (Rubric)
  scoring_rubric:
    weights:               
      security: 40
      readability: 30
      performance: 30

    security:
      critical_vulnerability_score: 0

    readability:
      thresholds:
        - complexity: 5
          points: 30
        - complexity: 10
          points: 20
        - complexity: 15
          points: 10

    performance:
      improvement_thresholds:
        - improvement_percent: 20
          points: 30
        - improvement_percent: 10
          points: 20
        - improvement_percent: 5
          points: 10

#  로깅 설정
logging:
  level: "INFO" 
  file_path: "./results/logs/maestro_run.log"


