# -*- coding: utf-8 -*-
"""
MAESTRO 프레임워크의 Group B 실험(단일 LLM 개선)을 실행하는 스크립트입니다.
v_gen 코드를 입력받아 LLM에게 NFR 개선을 요청하고 결과를 저장합니다.
"""

import os
import argparse
import datetime
import json
from typing import Dict, Any

# --- 유틸리티 및 설정 ---
# 프로젝트 루트에서 실행된다고 가정하고 경로 설정
# (스크립트가 다른 위치에서 실행될 경우를 대비한 경로 조정 포함)
try:
    # `python -m src.scripts.run_group_b`로 실행될 경우
    from maestro.utils.file_io import read_yaml_file, read_text_file, write_text_file
    from maestro.utils.llm_handler import set_llm_provider, call_llm
except ImportError:
    # `python src/scripts/run_group_b.py`로 직접 실행될 경우
    import sys

    # 현재 파일의 상위 폴더(src)를 sys.path에 추가
    SRC_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    if SRC_DIR not in sys.path:
        sys.path.insert(0, SRC_DIR)
    # 이제 src.maestro... 형태로 import 시도
    from src.maestro.utils.file_io import (
        read_yaml_file,
        read_text_file,
        write_text_file,
    )
    from src.maestro.utils.llm_handler import set_llm_provider, call_llm


# --- Group B를 위한 간단한 프롬프트 ---
# 연구 계획서 B 그룹의 요구사항을 반영
SIMPLE_IMPROVEMENT_PROMPT = """
You are tasked with improving the Non-Functional Requirements (NFRs) of the following Python code, which was generated by another AI.
Your goal is to enhance its performance, readability, and security while strictly preserving its original functionality.

Original Code (`v_gen`):
```python
{v_gen_code}
```

Please refactor the code above to meet these NFR goals.
Output ONLY the refactored Python code within a single markdown code block (` ```python ... ``` `). Do not include any explanations before or after the code block.
Ensure the functionality remains identical to the original code.
"""  # <<< 누락된 코드 블록 닫기 및 문자열 닫기 추가


def extract_code_from_llm_response(response_str: str) -> str:
    """LLM 응답에서 Python 코드 블록을 추출합니다."""
    # ```python ... ``` 형식 우선 탐색
    if "```python" in response_str:
        start_tag = "```python"
        start_index = response_str.find(start_tag)
        if start_index != -1:
            end_tag = "```"
            end_index = response_str.find(end_tag, start_index + len(start_tag))
            if end_index != -1:
                return response_str[start_index + len(start_tag) : end_index].strip()

    # ``` ... ``` 형식 차선 탐색
    if "```" in response_str:
        start_tag = "```"
        start_index = response_str.find(start_tag)
        if start_index != -1:
            end_tag = "```"
            # 첫 번째 ``` 이후의 다음 ```를 찾음
            end_index = response_str.find(end_tag, start_index + len(start_tag))
            if end_index != -1:
                # 시작 마커 바로 다음부터 끝 마커 바로 앞까지 추출
                return response_str[start_index + len(start_tag) : end_index].strip()

    # 코드 블록 마커를 찾지 못한 경우, 응답 전체를 반환 (최후의 수단)
    print(
        "경고: LLM 응답에서 코드 블록 마커(```python 또는 ```)를 찾지 못했습니다. 전체 응답을 코드로 간주합니다."
    )
    return response_str.strip()


def run_simple_llm_enhancement(
    config: Dict[str, Any], input_code_path: str, output_dir: str
):
    """
    단일 LLM을 사용하여 코드의 NFR 개선을 시도합니다 (Group B).

    Args:
        config (Dict[str, Any]): 설정 딕셔너리.
        input_code_path (str): 개선할 코드(v_gen) 파일 경로.
        output_dir (str): 결과를 저장할 디렉토리 경로.
    """
    run_id = datetime.datetime.now().strftime("%Y%m%d_%H%M%S") + "_GroupB"
    print(f"\n===== Group B: 단일 LLM 개선 시작 (Run ID: {run_id}) =====")
    print(f"입력 코드: {input_code_path}")
    print(f"출력 디렉토리: {output_dir}")

    # 0. 출력 디렉토리 생성
    os.makedirs(output_dir, exist_ok=True)
    # 오류/실행 정보/최종 코드 저장을 위한 경로 정의
    error_report_path = os.path.join(output_dir, "error_report.json")
    run_info_path = os.path.join(output_dir, "run_info.json")
    final_code_path = os.path.join(output_dir, "improved_code_group_b.py")

    # 이전 실행의 오류 보고서가 있다면 삭제 (선택 사항)
    if os.path.exists(error_report_path):
        os.remove(error_report_path)

    v_gen_code = ""  # 변수 초기화
    llm_response_code = ""  # 변수 초기화
    final_code = ""  # 변수 초기화

    try:
        # 1. 입력 코드 로드
        v_gen_code = read_text_file(input_code_path)
        print(f"입력 코드 로드 완료 (길이: {len(v_gen_code)} 자)")

    except FileNotFoundError as e:
        print(f"오류: 입력 코드 파일을 찾을 수 없습니다 - {e}")
        error_report = {
            "run_id": run_id,
            "status": "FAILURE_INPUT_NOT_FOUND",
            "error": str(e),
        }
        write_text_file(error_report_path, json.dumps(error_report, indent=4))
        return  # 함수 종료

    # 2. LLM 설정 및 프롬프트 준비
    try:
        # LLM 공급자 설정 (API 키 로드 등)
        set_llm_provider(config["llm"])
        print(f"LLM 공급자 '{config['llm'].get('provider', 'N/A')}' 설정 완료.")
    except KeyError:
        print("오류: 설정 파일에 'llm' 섹션이 없습니다.")
        error_report = {
            "run_id": run_id,
            "status": "FAILURE_CONFIG_MISSING",
            "error": "LLM config section missing.",
        }
        write_text_file(error_report_path, json.dumps(error_report, indent=4))
        return  # 함수 종료
    except Exception as e:
        print(f"LLM 공급자 설정 중 오류 발생: {e}")
        error_report = {
            "run_id": run_id,
            "status": "FAILURE_LLM_SETUP",
            "error": str(e),
        }
        write_text_file(error_report_path, json.dumps(error_report, indent=4))
        return  # 함수 종료

    # 프롬프트 생성
    prompt = SIMPLE_IMPROVEMENT_PROMPT.format(v_gen_code=v_gen_code)
    messages = [
        {
            "role": "system",
            "content": "You are an expert AI assistant specializing in code refactoring for NFR improvement.",
        },
        {"role": "user", "content": prompt},
    ]

    # 3. LLM 호출 및 결과 추출
    try:
        print("LLM 호출 중...")
        llm_response_code = call_llm(messages, config["llm"])
        print(f"LLM 응답 수신 완료 (길이: {len(llm_response_code)} 자).")

        # LLM 응답에서 코드 블록 추출
        final_code = extract_code_from_llm_response(llm_response_code)

        if not final_code:  # 추출된 코드가 비어있는 경우
            print("경고: LLM 응답에서 유효한 코드를 추출하지 못했습니다.")
            raise ValueError("Extracted code is empty.")
        print(f"코드 추출 완료 (길이: {len(final_code)} 자).")

    except Exception as e:
        print(f"LLM API 호출 또는 코드 추출 중 오류 발생: {e}")
        error_report = {
            "run_id": run_id,
            "status": "FAILURE_LLM_CALL_OR_EXTRACTION",
            "error": str(e),
            # 디버깅을 위해 응답 앞부분 저장 (너무 길 경우 잘라서)
            "llm_response_preview": llm_response_code[:1000]
            + ("..." if len(llm_response_code) > 1000 else ""),
        }
        write_text_file(error_report_path, json.dumps(error_report, indent=4))
        return  # 함수 종료

    # 4. 결과 저장
    try:
        write_text_file(final_code_path, final_code)

        # 간단한 실행 정보 저장
        run_info = {
            "run_id": run_id,
            "status": "SUCCESS",
            "input_code_path": input_code_path,
            "output_code_path": final_code_path,
            "llm_provider": config.get("llm", {}).get("provider"),
            "llm_model": config.get("llm", {}).get("model"),
        }
        write_text_file(run_info_path, json.dumps(run_info, indent=4))

        print(f"개선된 코드가 '{final_code_path}'에 성공적으로 저장되었습니다.")
    except Exception as e:
        print(f"결과 저장 중 오류 발생: {e}")
        error_report = {
            "run_id": run_id,
            "status": "FAILURE_SAVING_RESULT",
            "error": str(e),
        }
        write_text_file(error_report_path, json.dumps(error_report, indent=4))

    print("===== Group B: 단일 LLM 개선 완료 =====")


# --- 스크립트 직접 실행 시 ---
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="MAESTRO Group B: 단일 LLM 코드 개선 실행기"
    )
    # 필수 인자
    parser.add_argument(
        "--input_code", type=str, required=True, help="입력 코드 파일 경로 (v_gen)"
    )
    parser.add_argument(
        "--output_dir", type=str, required=True, help="결과 저장 디렉토리 경로"
    )
    # 선택 인자
    parser.add_argument(
        "--config",
        type=str,
        default="config.yml",
        help="설정 파일 경로 (기본값: config.yml)",
    )

    args = parser.parse_args()

    # 스크립트 실행 시작 로깅
    print(f"스크립트 실행 시작: {datetime.datetime.now()}")
    print(f"설정 파일: {args.config}")

    try:
        # 1. 설정 파일 로드
        config = read_yaml_file(args.config)

        # 2. Group B 워크플로우 실행
        run_simple_llm_enhancement(
            config=config, input_code_path=args.input_code, output_dir=args.output_dir
        )
        print("스크립트 실행 완료.")

    except FileNotFoundError as e:
        print(f"\n[오류] 필수 파일을 찾을 수 없습니다: {e}")
        print("설정 파일 또는 입력 코드 파일 경로가 정확한지 확인하세요.")
    except Exception as e:
        print(f"\n실행 중 예상치 못한 오류 발생: {e}")
        # 상세 오류 추적을 위해 traceback 출력
        import traceback

        traceback.print_exc()
    finally:
        print(f"스크립트 실행 종료: {datetime.datetime.now()}")
